---
name: codde_workspace

packages:
  - apps/**
  - packages/**

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.
  analyze:
    exec: dart analyze .
  test:
    run: melos run test:select --no-select
    description: Run all Flutter tests in this project.
  coverage:
    run: |
      melos exec -- flutter test --coverage &&
      melos exec -- genhtml coverage/lcov.info --output-directory=coverage/
    packageFilters:
      dirExists: test
    description: Generate coverage for the selected package.
