name: controller_widget_api
description: Control-Oriented, Design and Development Environnement for python robotic projects.
version: 0.0.1+1
homepage: https://codde-pi.com

publish_to: "none"

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^6.5.4
  equatable: ^2.0.5
  uuid: ^3.0.7
  rxdart: ^0.27.5
  xml: ^6.2.2

dev_dependencies:
  build_runner: ^2.3.2