name: flame_socketio
description: Integration for the SocketIO library to Flame games.
version: 0.0.1
# homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_socketio

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flame: ^1.7.3
  flutter:
    sdk: flutter
  meta: ^1.7.00
  socket_io_client: ^2.0.0
  # socket_io: ^1.0.1

dev_dependencies:
  dartdoc: ^6.0.1
  flame_lint: ^0.2.0+2
  flame_test: ^1.10.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0