name: flame_coddecom
description: Integration for the C.O.D.D.E. Pi Com library to Flame games.
version: 0.0.1
# homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_socketio

publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  # local
  codde_com:
    path: ../codde_com
  
  flame: ^1.7.3
  meta: ^1.7.00

dev_dependencies:
  dartdoc: ^6.0.1
  flame_lint: ^0.2.0+2
  flame_test: ^1.10.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0