---
name: flame_mjpeg
description: Integration for the SocketIO library to Flame games.
version: 0.0.1
# homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_mjpeg
environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  # flame: ^1.7.3
  flame:
    path: ../flame/packages/flame
  http: ^1.1.0
  meta: ^1.9.1

dev_dependencies:
  dartdoc: ^6.0.1
  flame_lint: ^0.2.0+2
  flame_test: ^1.10.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
